version: '3'
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    container_name: shop-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - shop_db_data:/var/lib/postgresql/data
volumes:
  shop_db_data: