version: '3'
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    container_name: shop-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${SHOP_POSTGRES_PASSWORD}
      POSTGRES_USER: ${SHOP_POSTGRES_USER}
      POSTGRES_PORT: ${SHOP_POSTGRES_PORT}
      POSTGRES_DB: ${SHOP_POSTGRES_DB}
    volumes:
      - shop_db_data:/var/lib/postgresql/data
volumes:
  shop_db_data: